name: Test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Handover Bot
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
      PORT: 9621
      SLACK_APP_TOKEN: XXXX-X-XXXXXXXXXXX-XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      SLACK_BOT_TOKEN: XXXX-XXXXXXXXXXXXX-XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXX
      SLACK_SIGNING_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      HANDOVER_CHANNEL: XXXXXXXXXXX
      HANDOVER_TITLE: Dev Handover
      OPENAI_API_KEY: XX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Generate DB Types
        run: pnpm run prisma generate

      - name: Check Code Formatting
        run: pnpm run tidy:check

      - name: Typescript
        run: pnpm run build

      - name: Create test env file
        run: |
          cat > .env.test << EOF
          PORT=${{ env.PORT }}
          SLACK_APP_TOKEN=${{ env.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN=${{ env.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET=${{ env.SLACK_SIGNING_SECRET }}
          HANDOVER_CHANNEL=${{ env.HANDOVER_CHANNEL }}
          HANDOVER_TITLE=${{ env.HANDOVER_TITLE }}
          DATABASE_URL=postgresql://postgres:password@localhost:5432/runn_handover_test?schema=public
          OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}
          EOF

      - name: Setup test database
        run: pnpm run prisma:test db push

      - name: Migrate Database
        run: pnpm run prisma db push

      - name: Tests
        run: pnpm run test
